// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7Qx1svtkmy4WJiiBEl1Lq2CrpjyCtJE',
    appId: '1:818908261826:web:a22bdb65bd5bc91b547a5b',
    messagingSenderId: '818908261826',
    projectId: 'wismeresearchapp2',
    authDomain: 'wismeresearchapp2.firebaseapp.com',
    storageBucket: 'wismeresearchapp2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUThMmVJSVmVNMgyM8jHf4S7JS-ly0dGM',
    appId: '1:818908261826:android:dd29c5b65e88993b547a5b',
    messagingSenderId: '818908261826',
    projectId: 'wismeresearchapp2',
    storageBucket: 'wismeresearchapp2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3eQuJw9gkAtgwgQ2h6m-4NTPUNCbwik8',
    appId: '1:818908261826:ios:ee790ce4d4e39bf6547a5b',
    messagingSenderId: '818908261826',
    projectId: 'wismeresearchapp2',
    storageBucket: 'wismeresearchapp2.firebasestorage.app',
    iosClientId: '818908261826-576j7j20b66nt9bn2mrh4dvaag1mlm24.apps.googleusercontent.com',
    iosBundleId: 'com.example.researchapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3eQuJw9gkAtgwgQ2h6m-4NTPUNCbwik8',
    appId: '1:818908261826:ios:ee790ce4d4e39bf6547a5b',
    messagingSenderId: '818908261826',
    projectId: 'wismeresearchapp2',
    storageBucket: 'wismeresearchapp2.firebasestorage.app',
    iosBundleId: 'com.example.researchapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI7Qx1svtkmy4WJiiBEl1Lq2CrpjyCtJE',
    appId: '1:818908261826:web:c26183f81a269b98547a5b',
    messagingSenderId: '818908261826',
    projectId: 'wismeresearchapp2',
    authDomain: 'wismeresearchapp2.firebaseapp.com',
    storageBucket: 'wismeresearchapp2.firebasestorage.app',
  );

}